### ISSUE TITLE
[Question] Build instructions

### ISSUE THREAD

**Issue by yan12125** [darlinghq/darling-dmg#32]
What kind of compilers and standard libraries are recommended to build this project?

Seems it's tested primarily under clang. Is GCC acceptable? I've successfully mounted ```Xcode_7.0.1.dmg``` on Arch Linux with GCC 5.2.0. I'm using libstdc++ from GCC 5.2.0, too. Is libc++ preferable?

**Comment by yan12125** [comment]
PS. I'm the current maintainer of Arch Linux's [unofficial package](https://aur.archlinux.org/packages/darling-dmg-git/). I hope to hear recommended build instructions here so that I can improve the packaging script.

**Comment by LubosD** [comment]
Hi,

both GCC and Clang work fine as long as the given compiler version supports C++11. I've only tested with libstdc++.

**Comment by yan12125** [comment]
Thanks for the information!
