### ISSUE TITLE
Can't download links in https://www.darlinghq.org/build-instructions

### ISSUE THREAD

**Issue by miguelqvd** [darlinghq/darling-dmg#37]
Hi,

I've tried to download Debian and Ubuntu's pre-compiled packages but I'm always asked for username & password. Could you please do something about that?

I've also tried to rebuild the whole project in Ubuntu 16.04 but I've failed installing kernel modules as kernel headers are missing certs/signing_key.pem and certs/signing_key.x509 to sign the new modules.

Do you know how could I install the modules without recompiling the kernel?

Thanks a lot in advance for your support.

MAQ

**Comment by LubosD** [comment]
There are no pre-built packages for Debian and Ubuntu; what you see on the website is only build status.

You don't need to recompile the kernel to build the modules, but you may just need to disable module signing. I cannot really help you with that as I don't use Ubuntu.

**Comment by miguelqvd** [comment]
Thanks a lot for your reply! I didn't find the way to disable module signing without recompiling the kernel... It seems that I will have to recompile it tough. 

I'm very excited to try out your cool Project.
