### ISSUE TITLE
linking error in Ubuntu 16.04

### ISSUE THREAD

**Issue by kensully** [darlinghq/darling-dmg#40]
I am on Ubuntu 16.04 platform. I am trying to compile `osxcross`  package which it clones and builds `darling-dmg` but in linking process I get the following errors : 

    libdmg.so: undefined reference to `icu_58::ByteSink::Flush()'
    libdmg.so: undefined reference to `icu_58::UnicodeString::fromUTF8(icu_58::StringPiece)'
    libdmg.so: undefined reference to `icu_58::ByteSink::GetAppendBuffer(int, int, char*, int, int*)'
    libdmg.so: undefined reference to `icu_58::UnicodeString::extract(char*, int, UConverter*, UErrorCode&) const'
    libdmg.so: undefined reference to `ucnv_close_58'
    libdmg.so: undefined reference to `icu_58::UnicodeString::doCaseCompare(int, int, unsigned short const*, int, int, unsigned int) const'
    libdmg.so: undefined reference to `vtable for icu_58::UnicodeString'
    libdmg.so: undefined reference to `icu_58::UnicodeString::doCompare(int, int, unsigned short const*, int, int) const'
    libdmg.so: undefined reference to `icu_58::UnicodeString::UnicodeString(char const*, int, UConverter*, UErrorCode&)'
    libdmg.so: undefined reference to `icu_58::UnicodeString::toUTF8(icu_58::ByteSink&) const'
    libdmg.so: undefined reference to `icu_58::ByteSink::~ByteSink()'
    libdmg.so: undefined reference to `icu_58::UnicodeString::doEquals(icu_58::UnicodeString const&, int) const'
    libdmg.so: undefined reference to `icu_58::UnicodeString::UnicodeString(char const*, int, char const*)'
    libdmg.so: undefined reference to `typeinfo for icu_58::ByteSink'
    libdmg.so: undefined reference to `icu_58::UMemory::operator delete(void*)'
    libdmg.so: undefined reference to `ucnv_open_58'
    libdmg.so: undefined reference to `icu_58::UnicodeString::~UnicodeString()'
    libdmg.so: undefined reference to `icu_58::UnicodeString::moveFrom(icu_58::UnicodeString&)'

I installed `libicu-dev` in the repository (55.1.7) before I started compilation. 
Would you help me fix it?
Thanks.
Kenn

**Comment by LubosD** [comment]
I suspect you have multiple versions of ICU installed and it compiles against a different version than it (tries to) link to. `icu_58` refers to ICU 58 (and not 55.x).

**Comment by kensully** [comment]
@LubosD  You are right about it, I installed newer version of it from source I removed all the files including `pkgconfig` files in `/usr/local/lib` but I can not fix it in `usr/local/lib`. I wonder from where `cmake` find that library.
