### ISSUE TITLE
fatal error: 'fuse.h' file not found .. on linuxmint 18.2

### ISSUE THREAD

**Issue by TechComet** [darlinghq/darling-dmg#43]
darling-dmg/src/main-fuse.h:5:10: fatal error: 'fuse.h' file not found
#include <fuse.h>

sudo apt-get install linux-libc-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
linux-libc-dev is already the newest version (4.4.0-92.115).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

**But not work**

**Comment by LubosD** [comment]
Learn to use package search.

https://packages.ubuntu.com/search?searchon=contents&keywords=fuse.h&mode=exactfilename&suite=zesty&arch=any

The needed package is libfuse-dev.

**Comment by TechComet** [comment]
many files use fuse.h !
thank you .. I use apt-file
