### ISSUE TITLE
error: cannot decrement value of type 'HFSBTreeNode::RecordIterator<HFSBTree::Key>'

### ISSUE THREAD

**Issue by supagu** [darlinghq/darling-dmg#51]
I'm running manjaro, arch linux.
running the current head of darling-dmg I get the following error:

https://pastebin.com/UVxRikai

**Comment by LubosD** [comment]
Seems to be caused by GCC 8.1 present in your system (its libstdc++ is used).

**Comment by supagu** [comment]
gcc --version
gcc (GCC) 8.1.1 20180531

yep! so does the code need to be updated to support gcc or do I need to somehow specify some compile flags/environment vars or something to work around the issue?

**Comment by icebreaker** [comment]
@supagu See #55 for the change that "resolves" this issue.

**Comment by LubosD** [comment]
Fixed

**Comment by supagu** [comment]
yep its working for me now on master branch, ta
