### ISSUE TITLE
Hard link

### ISSUE THREAD

**Issue by jief666** [darlinghq/darling-dmg#54]
Hi,

Not an issue but a question.

I'd link to follow hard link, like os x does (while get xattr fro example).
The reference of a hard link is an inode number. Is there already a way to find file from its inode number ?

Thanks.

**Comment by LubosD** [comment]
I don't know much about hardlinks in HFS. I simply believed they work out of box.

Do they not work? I don't quite understand this:

> I'd link to follow hard link, like os x does (while get xattr fro example).

**Comment by jief666** [comment]
No they don't work. Got the answer.
A hard link has a type hlnk and it's referenced file "inode" number in ff.file.permissions.special.iNodeNum. Well, in fact, that's not an inode number. It's a number to construct a filename that is kept in \0\0\0\0HFS+ Private Data. Format is iNode + number.
So each access to a hlnk file must be redirect to this "iNode file".

**Comment by tomkoen** [comment]
is it solved?

**Comment by jief666** [comment]
Yes, it's now supported.
