### ISSUE TITLE
Strange HFSX files inside IPSW firmware

### ISSUE THREAD

**Issue by tomkoen** [darlinghq/darling-dmg#62]
IPSW iOS firmware [files](https://ipsw.me/#!/download) contain number of DMG files, which are actually simple HFSX raw file system.
Examples: 
https://www.dropbox.com/s/0zpx0b52thrfawm/058-97112-138.dmg?dl=0
https://www.dropbox.com/s/tcc0qhn27md1njp/058-97541-138.dmg?dl=0

The problem is that these files have special 27 bytes offset before actual HFS data:
![sshot-2018-07-08- 15-25-12](https://user-images.githubusercontent.com/7878850/42420248-20311bd6-82c3-11e8-95f0-3a5347177b92.png)

7Zip is smart to handle such files, but in my code I have to do the following tweak:
```
ioReader->setStartOffset((ioReader->length() % 512));
```

Is it OK? Can this be implemented in the lib? 

Thank you

**Comment by LubosD** [comment]
This change does not look safe, I'd instead detect this unusual header.

**Comment by tomkoen** [comment]
You're right, thanks for the advice.
