### ISSUE TITLE
LZFSE is not supported

### ISSUE THREAD

**Issue by zivkaspersky** [darlinghq/darling-dmg#88]
I think its because the compression of some section in the DMG is LZFSE

```
Darling [~/Documents]$ hdiutil attach 9bcf01399719755034c964549a6a3af38932e7eaf03febc8b3742306505ca8a9 
Skipping partition of type Apple_partition_map
Using partition #1 of type Apple_HFS
Error: Unexpected EOF from readRun

Possible reasons:
1) The file is corrupt.
2) The file is not really a DMG file, although it resembles one.
3) There is a bug in darling-dmg.
```

[link to DMG](https://drive.google.com/file/d/12oxYjDHuw6TQaMZmxtJsBuDqd5zOsJnO/view?usp=sharing)
*do take care this dmg might contain a malware

**Comment by kleuter** [comment]
Please see the COMPILE_WITH_LZFSE compile switch

**Comment by tomkoen** [comment]
Please see the COMPILE_WITH_LZFSE compile switch

**Comment by LubosD** [comment]
I'm afraid this compile switch is not yet used in the hdiutil build.

**Comment by zivkaspersky** [comment]
So it's already developed and still wasn't released?

**Comment by LubosD** [comment]
Basically yes, because releasing it for Darling (and not just for use outside of Darling) requires adding liblzfse to the build, which hasn't been done yet.

**Comment by ahyattdev** [comment]
Works now
