### ISSUE TITLE
Build fail when using not using Darling prefix while Apple is defined

### ISSUE THREAD

**Issue by ElielCohen** [darlinghq/darling-dmg#89]
Hi Everyone,

https://github.com/darlinghq/darling-dmg/blob/97a92a6930e43cdbc9dedaee62716e3223deb027/src/main-fuse.cpp#L287

Basically we should have in line 286 : 
#if defined(__APPLE__) && !defined(DARLING)
And not like now only :
#if defined(__APPLE__)

Because if we are in a case where both Apple is defined and DARLING is not, then, we won't have the position variable defined, and it will crash at build time showing that error :

/workdir/darling/src/external/darling-dmg/src/main-fuse.cpp:287:6: error: use of undeclared identifier 'position'

Should I open a PR for this, or is someone else can fix it ?

Thanks :)

Eliel

**Comment by bugaevc** [comment]
Looks like this one was overlooked in https://github.com/darlinghq/darling-dmg/commit/1b69c1bba7f2a4c31b05c75bfe3657c3cf88e5f8, thanks!

**Comment by ElielCohen** [comment]
Have made a PR for it : https://github.com/darlinghq/darling-dmg/pull/90
